version: '3.3'
services:
  redis:
    image: 'docker.uclv.cu/redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

    expose:
      - 6379

  chord:
    build: .
    links:
      - redis
    container_name: chord_dht-container
